-- .SQL resource only valid for in memory database
INSERT INTO USER_DETAILS (ID, BIRTH_DATE, NAME) VALUES (10001, CURRENT_DATE(), 'Mohsin');
INSERT INTO USER_DETAILS (ID, BIRTH_DATE, NAME) VALUES (10002, CURRENT_DATE(), 'Ali');
INSERT INTO USER_DETAILS (ID, BIRTH_DATE, NAME) VALUES (10003, CURRENT_DATE(), 'Hassan');

INSERT INTO POST (ID, DESCRIPTION, USER_ID) VALUES (20001, 'I want to learn AWS', 10001);
INSERT INTO POST (ID, DESCRIPTION, USER_ID) VALUES (20002, 'I want to learn DevOps', 10001);

INSERT INTO POST (ID, DESCRIPTION, USER_ID) VALUES (20003, 'I want to learn CI/CD', 10002);
INSERT INTO POST (ID, DESCRIPTION, USER_ID) VALUES (20004, 'I want to learn Java', 10002);